"""alter Game.game_picture to varchar(url)

Revision ID: 5818f9452c7b
Revises: b74c426abc64
Create Date: 2022-12-26 22:42:58.738383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5818f9452c7b'
down_revision = 'b74c426abc64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_picture',
               existing_type=sa.BLOB(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_picture',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
