"""create new table

Revision ID: 79757c2ccea0
Revises: eb4f50994d04
Create Date: 2022-12-08 22:42:28.664726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79757c2ccea0'
down_revision = 'eb4f50994d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('create_at', sa.DATE(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), nullable=False),
    sa.Column('authority', sa.Enum('Admin', 'Developer', 'Member', name='authority'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('member_balance', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('create_at', sa.DATE(), nullable=False),
    sa.Column('game_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('game_sale_price', sa.INTEGER(), nullable=False),
    sa.Column('game_developer', sa.VARCHAR(length=20), nullable=False),
    sa.Column('game_picture', sa.BLOB(), nullable=False),
    sa.Column('game_introduction', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('game_discount', sa.DECIMAL(), nullable=True),
    sa.Column('game_genre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('game_version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('game_developer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_developer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('cart',
    sa.Column('cart_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('cost', sa.INTEGER(), nullable=False),
    sa.Column('place_order', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('game_list',
    sa.Column('game_list_id', sa.INTEGER(), nullable=False),
    sa.Column('create_at', sa.DATE(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game_list_type', sa.Enum('Wishlist', 'Library', name='game_list_type'), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=200), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('game_list_id')
    )
    op.create_table('issue',
    sa.Column('issue_id', sa.INTEGER(), nullable=False),
    sa.Column('create_at', sa.DATE(), nullable=False),
    sa.Column('issue_type', sa.Enum('Violation', 'Refund', name='issue_type'), nullable=False),
    sa.Column('issue_deleted_at', sa.DATE(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('violation_content', sa.VARCHAR(length=200), nullable=True),
    sa.Column('refund_acception', sa.Boolean(), nullable=True),
    sa.Column('refund_gameId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['refund_gameId'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue')
    op.drop_table('game_list')
    op.drop_table('cart')
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
