"""revise password size

Revision ID: 99e7b64714bd
Revises: 79757c2ccea0
Create Date: 2022-12-16 21:50:58.877722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99e7b64714bd'
down_revision = '79757c2ccea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('name', 'user', ['name'], schema='User')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.drop_constraint('uq_user_name', 'user', schema='User')

    # ### end Alembic commands ###
